# Examen Python Avanzado
Hola a todos, estos serán los ejercicios que deberán hacer de la parte de módulos científicos (:

### NumPy

In [2]:
import numpy as np

1) Crea un array de cuatros cuyo atributo shape sea (5,3,2)

2) Elabora una función que reciba número de filas y columnas y regrese un arreglo con dicho tamaño, con una distribución de 0 y 1 como tablero de ajedrez

    Ejemplo: [In]: (3,6)  [Out]: array([[1., 0., 1., 0., 1., 0.],
                                       [0., 1., 0., 1., 0., 1.],
                                       [1., 0., 1., 0., 1., 0.]])

3) A partir de los siguientes arreglos:

In [13]:
m1 = np.arange(9).reshape([3, 3])
m2 = np.arange(9, 18).reshape([3, 3])
print("La matriz m1 es:")
print(m1)
print("La matriz m2 es:")
print(m2)

La matriz m1 es:
[[0 1 2]
 [3 4 5]
 [6 7 8]]
La matriz m2 es:
[[ 9 10 11]
 [12 13 14]
 [15 16 17]]


Crea los siguientes arreglos:


    1)
     [[ 0  1  2]
     [ 3  4  5]
     [ 6  7  8]
     [ 9 10 11]
     [12 13 14]
     [15 16 17]]

    2) 
     [[ 0  1  2  9 10 11]
     [ 3  4  5 12 13 14]
     [ 6  7  8 15 16 17]]

4) Escribe una función que reciba una matriz y regrese True sí es una matriz identidad y un False si no es así

        Ejemplo: [In]:[[1., 0., 0., 0.],                  [Out]: True
                       [0., 1., 0., 0.],
                       [0., 0., 1., 0.],
                       [0., 0., 0., 1.]]

5) Haz una función que reciba una matriz y número, luego que te regrese una matriz donde te de un True si el 
elemento es mayor que el número ingresado y False si es menor

    Ejemplo:  [In]: [[15, 85, 103, 444, 150, 200, 35, 47],      
                     [532, 476, 0, 1011, 50, 674, 5, 999],
                     [985, 7, 99, 101, 1, 58, 300, 78],
                     [750, 649, 86, 8, 505, 41, 745, 187]]
              [In]: 100
                     
              [Out]:  [[False, False,  True,  True,  True,  True, False, False],
                       [ True,  True, False,  True, False,  True, False,  True],
                       [ True, False, False,  True, False, False,  True, False],
                       [ True,  True, False, False,  True, False,  True,  True]]

### Pandas

In [15]:
import pandas as pd

In [20]:
datos = {
    'fecha':pd.date_range('20200113', periods=6),
    'experiencia':pd.Categorical(['buena', 'muy buena', 'mala', 'buena', 'muy mala', 'buena'],
                                ["muy mala", "mala", "regular", "buena", "muy buena"]),
    'monto':[120, 23.34, 123.34, 343.2, 23.4, 343.3],
    'propina':[10, 5, 12, 45, 0, 30],
    'opinion':['fria la comida', 'espere mucho tiempo', 'todo bien', 'excelente', 'mal servicio', 'Tardaron mucho']
}
df = pd.DataFrame(datos)
df.experiencia.cat.categories

Index(['muy mala', 'mala', 'regular', 'buena', 'muy buena'], dtype='object')

1) A partir de los datos de arriba muestra el promedio de la propian que reciben

2) Muestra los datos de todas aquellas entradas que en la que la experiencia fue buena

3) Despliega todos los datos menos el primero

4) Ingresa a la columna de opinión usando la función loc y usando la función iloc

5) Explica cuál es la diferencia entre usar loc y usar iloc

### Sympy

1)Definir la formula general de segundo grado, definir las variables necesarias

2) Resolver la siguiente ecuación:
$$-x^{2}+7x-10 = 0$$

3) Resolver la siguiente integral :

$$F(x)=∫ x^{\pi−1} f(x)dx$$

### Scipy

1) Definir 5 constantes nuevas diferentes a las vistas en clase

2) Obten los mínimos cuadrados de:
$$x^{4}+7x^{2}+17$$

### Matplotlib

1) Crea un gráfico que se vea como el siguiente:
![](https://drive.google.com/uc?id=1zFKbPx-qH12UEfZHEHkxMhAyuU-96I0G)

2) Crea un gráfico con dos funciones seno que se vea de esta manera
![cosenos](https://drive.google.com/uc?id=1tSNHiQgbpth21rOEHmVu3FPLts7W1gAh)

3) Realiza una gráfica con x contra x, x al cuadrado y x cúbica.

![grafica x](https://drive.google.com/uc?id=1Jyag35ne8a3CqaJXzB_L3mlp3dA0VtI0)

4) Crea la gráfica anterior pero ahora con líneas punteadas

5) Visita la siguiente página: https://python-graph-gallery.com/matplotlib/


Es una galeria de distintas gráficas hechas en matplotlib, puedes acceder al código, elige una y agregala comentandola en español 